name: CI Java
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Run a one-line script
        run: echo Hello from Lab Final
        
